name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # O la rama que uses

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Firebase Secrets
        run: |
          sed -i 's/REPLACE_FIREBASE_API_KEY/${{ secrets.FIREBASE_API_KEY }}/g' index.html
          sed -i 's/REPLACE_FIREBASE_AUTH_DOMAIN/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g' index.html
          sed -i 's#REPLACE_FIREBASE_DATABASE_URL#${{ secrets.FIREBASE_DATABASE_URL }}#g' index.html
          sed -i 's/REPLACE_FIREBASE_PROJECT_ID/${{ secrets.FIREBASE_PROJECT_ID }}/g' index.html
          sed -i 's/REPLACE_FIREBASE_STORAGE_BUCKET/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g' index.html
          sed -i 's/REPLACE_FIREBASE_MESSAGING_SENDER_ID/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g' index.html
          sed -i 's/REPLACE_FIREBASE_APP_ID/${{ secrets.FIREBASE_APP_ID }}/g' index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Sube la carpeta actual
          branch: gh-pages # Se publicar√° en esta rama
